src/Entity/FicheFrais.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FicheFraisRepository")
 */
class FicheFrais
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $mois;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbJustificatifs;

    /**
     * @ORM\Column(type="float")
     */
    private $montantValide;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateModification;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="ficheFrais")
     */
    private $fk_users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneFraisForfait", mappedBy="fk_FicheFrais", cascade={"persist"})
     */
    private $ligneFraisForfaits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneFraisHorsForfait", mappedBy="fk_FicheFrais", cascade={"persist"})
     */
    private $ligneFraisHorsForfaits;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etat", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_Etat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Vehicule", inversedBy="ficheFrais")
     */
    private $fk_vehicule;

    /**
     * @ORM\Column(type="float")
     */
    private $montantTotal;

    public function __construct()
    {
        $this->ligneFraisForfaits = new ArrayCollection();
        $this->ligneFraisHorsForfaits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMois(): ?\DateTimeInterface
    {
        return $this->mois;
    }

    public function setMois(\DateTimeInterface $mois): self
    {
        $this->mois = $mois;

        return $this;
    }

    public function getNbJustificatifs(): ?int
    {
        return $this->nbJustificatifs;
    }

    public function setNbJustificatifs(int $nbJustificatifs): self
    {
        $this->nbJustificatifs = $nbJustificatifs;

        return $this;
    }

    public function getMontantValide(): ?float
    {
        return $this->montantValide;
    }

    public function setMontantValide(float $montantValide): self
    {
        $this->montantValide = $montantValide;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->dateModification;
    }

    public function setDateModification(\DateTimeInterface $dateModification): self
    {
        $this->dateModification = $dateModification;

        return $this;
    }

    public function getFkUsers(): ?Users
    {
        return $this->fk_users;
    }

    public function setFkUsers(?Users $fk_users): self
    {
        $this->fk_users = $fk_users;

        return $this;
    }

    /**
     * @return Collection|LigneFraisForfait[]
     */
    public function getLigneFraisForfaits(): Collection
    {
        return $this->ligneFraisForfaits;
    }

    public function addLigneFraisForfait(LigneFraisForfait $ligneFraisForfait): self
    {
        if (!$this->ligneFraisForfaits->contains($ligneFraisForfait)) {
            $this->ligneFraisForfaits[] = $ligneFraisForfait;
            $ligneFraisForfait->setFkFicheFrais($this);
        }

        return $this;
    }

    public function removeLigneFraisForfait(LigneFraisForfait $ligneFraisForfait): self
    {
        if ($this->ligneFraisForfaits->contains($ligneFraisForfait)) {
            $this->ligneFraisForfaits->removeElement($ligneFraisForfait);
            // set the owning side to null (unless already changed)
            if ($ligneFraisForfait->getFkFicheFrais() === $this) {
                $ligneFraisForfait->setFkFicheFrais(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LigneFraisHorsForfait[]
     */
    public function getLigneFraisHorsForfaits(): Collection
    {
        return $this->ligneFraisHorsForfaits;
    }

    public function addLigneFraisHorsForfait(LigneFraisHorsForfait $ligneFraisHorsForfait): self
    {
        if (!$this->ligneFraisHorsForfaits->contains($ligneFraisHorsForfait)) {
            $this->ligneFraisHorsForfaits[] = $ligneFraisHorsForfait;
            $ligneFraisHorsForfait->setFkFicheFrais($this);
        }

        return $this;
    }

    public function removeLigneFraisHorsForfait(LigneFraisHorsForfait $ligneFraisHorsForfait): self
    {
        if ($this->ligneFraisHorsForfaits->contains($ligneFraisHorsForfait)) {
            $this->ligneFraisHorsForfaits->removeElement($ligneFraisHorsForfait);
            // set the owning side to null (unless already changed)
            if ($ligneFraisHorsForfait->getFkFicheFrais() === $this) {
                $ligneFraisHorsForfait->setFkFicheFrais(null);
            }
        }

        return $this;
    }

    public function getFkEtat(): ?Etat
    {
        return $this->fk_Etat;
    }

    public function setFkEtat(?Etat $fk_Etat): self
    {
        $this->fk_Etat = $fk_Etat;

        return $this;
    }

    public function getFkVehicule(): ?Vehicule
    {
        return $this->fk_vehicule;
    }

    public function setFkVehicule(?Vehicule $fk_vehicule): self
    {
        $this->fk_vehicule = $fk_vehicule;

        return $this;
    }

    public function __toString() {
      return 'test';
    }

    public function getMontantTotal(): ?float
    {
        return $this->montantTotal;
    }

    public function setMontantTotal(?float $montantTotal): self
    {
        $this->montantTotal = $montantTotal;

        return $this;
    }
}

src/Controller/FicheFraisController.php
<?php

namespace App\Controller;

use App\Entity\FicheFrais;
use App\Entity\LigneFraisForfait;
use App\Entity\LigneFraisHorsForfait;
use App\Entity\FraisForfait;
use App\Entity\Users;
use App\Entity\Etat;
use App\Entity\Justificatif;
use App\Form\FicheFraisType;
use App\Repository\FicheFraisRepository;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/fichefrais")
 */
class FicheFraisController extends AbstractController
{

    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/", name="fiche_frais_index", methods={"GET"})
     */
    public function index(FicheFraisRepository $ficheFraisRepository): Response
    {
          // Si on est comptable on récupère toutes les fiches frais
        if($this->session->get('role') === "Comptable") {
          $fichefrais = $ficheFraisRepository->findAll();
          // Si on est visiteur on récupère les fiches liés à l'utilisateur et disponible en saisie
        } else {
          $fichefrais = $ficheFraisRepository->findBy([
            'fk_users' => $this->session->get('id'),
            'fk_Etat' => $this->getDoctrine()->getRepository(Etat::class)->findOneBy(['libelle' => 'Saisie'])
          ]);
        }
        return $this->render('fiche_frais/index.html.twig', [
            'fiche_frais' => $fichefrais,
        ]);
    }

    /**
     * @Route("/new", name="fiche_frais_new", methods={"GET","POST"})
     */
    public function new(Request $request, FicheFraisRepository $ficheFraisRepository): Response
    {
        if($this->session->get('role') === "Visiteur") { // Seul les visiteurs peuvent créer des fiches de frais
          $ficheFrai = new FicheFrais();
          /* Redirige sur l'edit si FF déjà existante */
          if($ficheFraisRepository->existThisCurrentMonth() && false) {
            $ficheFrai = $ficheFraisRepository->findLast();
            return $this->redirectToRoute('fiche_frais_edit', ['id' => $ficheFrai->getId()]);
          }

          /* Sinon on traite */
          $ficheFrai->setMois(new \DateTime());
          $ficheFrai->setMontantValide(0);
          $ficheFrai->setFkEtat($this->getDoctrine()->getRepository(Etat::class)->findOneBy(['libelle' => 'Saisie']));

          // Pour chaque Frais Forfait qu'on trouve en bdd, on ajoute une ligne frais forfait dans l'objet fiche de frais
          $arrayFraisForfait = $this->getDoctrine()->getRepository(FraisForfait::class)->findAll();
          foreach ($arrayFraisForfait as $oneFraisForfait) {
            $ligneFraisForfait = new LigneFraisForfait();
            $ligneFraisForfait->setDateMois($ficheFrai->getMois());
            $ligneFraisForfait->setFkFraisForfait($oneFraisForfait);
            $ligneFraisForfait->setEtatValidationLigne(false);
            $ficheFrai->getLigneFraisForfaits()->add($ligneFraisForfait);
          }

            // La création du form fiche de frais entrainera celui des lignes frais forfait et hors forfait
            // (voir FicheFraisType.php)
          $formFiche = $this->createForm(FicheFraisType::class, $ficheFrai);
            // Traitement lors du POST
          $formFiche->handleRequest($request);
          if ($formFiche->isSubmitted() && $formFiche->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
                      // ----- Fiche Frais ----- //
            $ficheFrai->setFkUsers($this->getDoctrine()->getRepository(Users::class)->find($this->session->get('id')));
            $ficheFrai->setDateModification(new \DateTime());
            $entityManager->persist($ficheFrai);
            $totalFF = 0;
            $nbJustificatif = 0;
            $i = 0;
                      // ----- Ligne Frais Forfait ----- //
            foreach ($ficheFrai->getLigneFraisForfaits() as $uneLigne) {
              $uneLigne->setFkFicheFrais($ficheFrai);
              $totalFF += $uneLigne->getQuantite()*$uneLigne->getMontantFrais();
            }
                      // ----- Ligne Frais Hors Forfait ----- //
            foreach ($ficheFrai->getLigneFraisHorsForfaits() as $uneLigneHF) {
                // Traitement justificatif
              $currentJustificatif = $formFiche['ligneFraisHorsForfaits'][$i]['justificatif']->getData();
              $i++;
              if ($currentJustificatif) {
                $nbJustificatif++;
                $originalFilename = pathinfo($currentJustificatif->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$currentJustificatif->guessExtension();
                $currentJustificatif->move($this->getParameter('justificatifs_directory'),$newFilename);
                $newJustificatif = new Justificatif();
                $newJustificatif->setFkUser(
                  $this->getDoctrine()->getRepository(Users::class)->find($this->session->get('id'))
                );
                $newJustificatif->setLigneFraisHorsForfait($uneLigneHF);
                $newJustificatif->setDateAjout(new \DateTime());
                $newJustificatif->setChemin($newFilename);
                $uneLigneHF->setFkJustificatif($newJustificatif);
              }
              $uneLigneHF->setDateMois($ficheFrai->getMois());
              $uneLigneHF->setFkFicheFrais($ficheFrai);
              $totalFF += $uneLigneHF->getMontant();
            }
            $ficheFrai->setMontantTotal($totalFF);
            $ficheFrai->setNbJustificatifs($nbJustificatif);
              // Fin des changements, enregistrement en BDD
            $entityManager->flush();
            return $this->redirectToRoute('fiche_frais_index');
          }

          return $this->render('fiche_frais/new.html.twig', [
          'fiche_frai' => $ficheFrai,
          'form' => $formFiche->createView(),
          'listeFraisForfait' => $arrayFraisForfait
          ]);
        } else {
          return $this->redirectToRoute('dashboard');
        }
    }

    /**
     * @Route("/{id}", name="fiche_frais_show", methods={"GET"})
     */
    public function show(FicheFrais $ficheFrai): Response
    {
        return $this->render('fiche_frais/show.html.twig', [
            'fiche_frai' => $ficheFrai,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="fiche_frais_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, FicheFrais $ficheFrai): Response
    {
        $arrayFraisForfait = $this->getDoctrine()->getRepository(FraisForfait::class)->findAll();
        $form = $this->createForm(FicheFraisType::class, $ficheFrai);
        $justificatifsChemin = [];

          // On récupère les lignes hors forfaits avant modifications pour assurer la persistence une fois qu'on submit
        $originalLHFs = new ArrayCollection();
        foreach ($ficheFrai->getLigneFraisHorsForfaits() as $originalLHF) {
            // Il semble que Symfony ne charge pas directement toutes les données intriquées lorsque l'on instancie un objet, à la place il effectue
            // un 'lazy loading'. Pour contourner ça, on effectue manuellement une requete pour qu'il aille chercher les données nécessaires.
            // Plus d'infos ici => https://symfony.com/doc/current/doctrine/associations.html#fetching-related-objects
          $justificatifsChemin[] = $originalLHF->getFkJustificatif()->getChemin();
          $originalLHFs->add($originalLHF);
        }

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
              // On vérifie si il y a des LHF a supprimées en comparant les LHF originels et celles en cours
            foreach ($originalLHFs as $LHF) {
              if ($ficheFrai->getLigneFraisHorsForfaits()->contains($LHF) === false) {
                $entityManager->remove($LHF);
              }
            }
              // Set les valeurs par defaut
            $ficheFrai->setDateModification(new \DateTime());
            $ficheFrai->setNbJustificatifs(sizeof($ficheFrai->getLigneFraisHorsForfaits()));
            $totalFF = 0; // Variables qui va récupérer les differents montants sur les lignes
            $totalValideFF = 0; // Pareil pour les frais validés
            $nbJustificatif = 0;
            $i = 0;
            foreach ($ficheFrai->getLigneFraisForfaits() as $uneLigne) {
              $uneLigne->setFkFicheFrais($ficheFrai);
              $totalFF += $uneLigne->getQuantite()*$uneLigne->getMontantFrais();
              if ($uneLigne->getEtatValidationLigne()) $totalValideFF += $uneLigne->getQuantite()*$uneLigne->getMontantFrais();
            }
            foreach ($ficheFrai->getLigneFraisHorsForfaits() as $uneLigneHF) {
                // Traitement justificatif
              if($this->session->get('role') === "Visiteur") {
                $currentJustificatif = $form['ligneFraisHorsForfaits'][$i]['justificatif']->getData();
                $i++;
                if ($currentJustificatif) {
                  $nbJustificatif++;
                  $originalFilename = pathinfo($currentJustificatif->getClientOriginalName(), PATHINFO_FILENAME);
                  $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                  $newFilename = $safeFilename.'-'.uniqid().'.'.$currentJustificatif->guessExtension();

templates/fiche_frais/_delete_form.html.twig
<form method="post" action="{{ path('fiche_frais_delete', {'id': fiche_frai.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche_frai.id) }}">
    <button class="btn btn-secondary">Delete</button>
</form>

templates/fiche_frais/_form.html.twig
{{ form_start(form) }}

  <div class="form-group">
    <label>Mois </label>
    {{ form_widget(form.mois) }}
  </div>

  {% if app.session.get('role') == "Comptable" %}
    <div class="form-group">
      <label>Etat</label>
      {{ form_widget(form.fk_etat) }}
    </div>
  {% endif %}

  <div class="form-group">
    <label>CV Fiscaux </label>
    {{ form_widget(form.fk_vehicule) }}
  </div>

  <h5>Ligne Frais Forfait </h5>

  <div class="form-group">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Libelle</th>
          <th scope="col">Montant</th>
          <th scope="col">Quantite</th>
          {% if app.session.get('role') == "Comptable" %}
            <th scope="col" style="text-align: center;">Validé</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for uneLigne in form.ligneFraisForfaits %}
          <tr>
            <th scope="row">{{ listeFraisForfait[loop.index - 1].libelle }}</th>
            <td>{{ listeFraisForfait[loop.index - 1].montant }}</td>
            <td>{{ form_widget(uneLigne.quantite) }}</td>
            {% if app.session.get('role') == "Comptable" %}
              <td style="text-align: center;">{{ form_widget(uneLigne.etatValidationLigne) }}</td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <h5>Ligne Frais Hors Forfait </h5>

  {% if app.session.get('role') == "Visiteur" %}
    <div>
      <i id="js-add-button" style="font-size: 1.8rem; cursor: pointer;" class="fas fa-plus-square"></i>
      <i id="js-remove-button" style="font-size: 1.8rem; cursor: pointer;" class="fas fa-minus-square"></i>
    </div>
  {% endif %}

  <div>
    <ul id="js-container-LHF" data-prototype="{{ form_widget(form.ligneFraisHorsForfaits.vars.prototype)|e('html_attr') }}">
      {% for uneLigne in form.ligneFraisHorsForfaits %}
        <li id="js-LHF-{{ loop.index }}">
          <div style="margin: 30px;"><b>LHF n°{{ loop.index }} :</b></div>
          {{ form_row(uneLigne) }}
          {% if justificatifsChemin[loop.index - 1] %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalJustificatif">Voir justificatif</button>
            <div class="modal fade" id="modalJustificatif" tabindex="-1" role="dialog" aria-labelledby="modalJustificatifCentered" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Justificatif n°{{ loop.index }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body text-center">
                    <img src="{{ asset('uploads/justificatifs/' ~ justificatifsChemin[loop.index - 1]) }}">
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  </div>

  {{ form_row(form.save, { 'label': button_label|default('Sauvegarder') }) }}

{{ form_end(form) }}

templates/fiche_frais/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche Frais{% endblock %}

{% block titrepage %} Modification Fiche de Frais {% endblock %}

{% block body %}

  <div style="width:75%; margin: auto;">
    {% if app.session.get('role') == "Comptable" %}
      {{ include('fiche_frais/_form.html.twig', {'button_label': 'Valider'}) }}
    {% else %}
      {{ include('fiche_frais/_form.html.twig', {'button_label': 'Modifier'}) }}
    {% endif %}
  </div>

{% endblock %}

{% block javascripts %}
  <script src="/js/addLHF.js" type="text/javascript"></script>
{% endblock %}

templates/fiche_frais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche Frais{% endblock %}

{% block titrepage %} Liste des Fiches de Frais {% endblock %}

{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th>Mois</th>
                <th>Montant Total</th>
                <th>Etat</th>
                <th>Montant Validé</th>
                <th>Nombres de justificatifs</th>
                <th>Dernière modification</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche_frai in fiche_frais %}
            <tr>
                <td>{{ fiche_frai.mois ? fiche_frai.mois|date('F Y') : '' }}</td>
                <td>{{ fiche_frai.montantTotal }}€</td>
                <td>{{ fiche_frai.fkEtat }}</td>
                <td>{{ fiche_frai.montantValide }}€</td>
                <td>{{ fiche_frai.nbJustificatifs }}</td>
                <td>{{ fiche_frai.dateModification ? fiche_frai.dateModification|date('d/m/Y') : '' }}</td>
                <td>
                    <a href="{{ path('fiche_frais_show', {'id': fiche_frai.id}) }}"><i class="far fa-eye"></i></a>
                    <a href="{{ path('fiche_frais_edit', {'id': fiche_frai.id}) }}"><i class="fas fa-pencil-alt"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7" class="text-center">Il n'y a actuellement pas de fiches de frais.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if app.session.get('role') == "Visiteur" %}
      <a class="btn btn-info" href="{{ path('fiche_frais_new') }}">Ajouter une nouvelle fiche <i class="fas fa-sticky-note"></i></a>
    {% endif %}
{% endblock %}

templates/fiche_frais/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche Frais{% endblock %}

{% block titrepage %} Création Fiche de Frais {% endblock %}

{% block body %}

  <div style="width:75%; margin: auto;">
    {{ include('fiche_frais/_form.html.twig', {'button_label': 'Sauvegarder'}) }}
  </div>

{% endblock %}

{% block javascripts %}
  <script src="/js/addLHF.js" type="text/javascript"></script>
{% endblock %}

templates/fiche_frais/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FicheFrais{% endblock %}

{% block body %}
    <h1>FicheFrais</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fiche_frai.id }}</td>
            </tr>
            <tr>
                <th>Mois</th>
                <td>{{ fiche_frai.mois ? fiche_frai.mois|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>NbJustificatifs</th>
                <td>{{ fiche_frai.nbJustificatifs }}</td>
            </tr>
            <tr>
                <th>MontantValide</th>
                <td>{{ fiche_frai.montantValide }}</td>
            </tr>
            <tr>
                <th>DateModification</th>
                <td>{{ fiche_frai.dateModification ? fiche_frai.dateModification|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('fiche_frais_index') }}">back to list</a>

    <a href="{{ path('fiche_frais_edit', {'id': fiche_frai.id}) }}">edit</a>

    {{ include('fiche_frais/_delete_form.html.twig') }}
{% endblock %}